development:
  adapter: async

test:
  adapter: async

production:
  adapter: async
  url: redis://redistogo:10d91696edc128925e0aba79dd73a1e9@pearlfish.redistogo.com:9832/
  channel_prefix: instatalk_production
