development:
  adapter: async

test:
  adapter: async

production:
  adapter: async
  url: redis://redistogo:dde16f59753c2ff5dcd2680b2c517dff@porgy.redistogo.com:11469/
  channel_prefix: instatalk_production
